/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JDateChooser;
import dao.ConnectionProvider;
import java.awt.Color;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.TemporalQueries.zoneId;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import utility.Myutility;
import java.sql.*;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author admin
 */
public class ViewAttendence extends javax.swing.JFrame {

    JDateChooser fromDate;
    JDateChooser toDate;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAttendence.class.getName());

    /**
     * Creates new form ViewAttendence
     */
    public ViewAttendence() {
        initComponents();

        javax.swing.JPopupMenu.setDefaultLightWeightPopupEnabled(false);

        Myutility.setImage(this, "images/abc1.jpg", 1251, 530);
        this.getRootPane().setBorder(
                BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK)
        );

        JPanel datePanel = new JPanel(null);
        datePanel.setOpaque(false);
        datePanel.setBounds(300, 90, 520, 60);

        fromDate = new JDateChooser();
        toDate = new JDateChooser();

        fromDate.setBounds(0, 20, 200, 32);
        toDate.setBounds(260, 20, 200, 32);

        fromDate.setDateFormatString("yyyy-MM-dd");
        toDate.setDateFormatString("yyyy-MM-dd");

        datePanel.add(fromDate);
        datePanel.add(toDate);

        getContentPane().add(datePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnExit1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAbsent = new javax.swing.JLabel();
        absentlbl = new javax.swing.JLabel();
        lblPresent = new javax.swing.JLabel();
        presentlbl = new javax.swing.JLabel();
        checkboxAddress = new javax.swing.JCheckBox();
        checkboxContact = new javax.swing.JCheckBox();
        checkboxState = new javax.swing.JCheckBox();
        checkboxCountry = new javax.swing.JCheckBox();
        checkboxUniqueRegID = new javax.swing.JCheckBox();
        btnResetFilters = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("     Attendence Track");

        btnExit1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit1.setText("X");
        btnExit1.addActionListener(this::btnExit1ActionPerformed);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(userTable);

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("On/From");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("To");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Search");

        lblAbsent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAbsent.setForeground(new java.awt.Color(255, 0, 0));
        lblAbsent.setText("------------");

        absentlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        absentlbl.setText("Absent");

        lblPresent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPresent.setForeground(new java.awt.Color(0, 255, 0));
        lblPresent.setText("-------------");

        presentlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        presentlbl.setText("Present");

        checkboxAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkboxAddress.setText("Address");
        checkboxAddress.addItemListener(this::checkboxAddressItemStateChanged);
        checkboxAddress.addActionListener(this::checkboxAddressActionPerformed);

        checkboxContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkboxContact.setText("Contact");
        checkboxContact.addItemListener(this::checkboxContactItemStateChanged);

        checkboxState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkboxState.setText("State");
        checkboxState.addItemListener(this::checkboxStateItemStateChanged);

        checkboxCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkboxCountry.setText("Coutry");
        checkboxCountry.addItemListener(this::checkboxCountryItemStateChanged);

        checkboxUniqueRegID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkboxUniqueRegID.setText("Unique Reg ID");
        checkboxUniqueRegID.addItemListener(this::checkboxUniqueRegIDItemStateChanged);

        btnResetFilters.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetFilters.setText("Reset Filters");
        btnResetFilters.addActionListener(this::btnResetFiltersActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(presentlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPresent))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(absentlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAbsent, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkboxContact)
                            .addComponent(checkboxAddress)
                            .addComponent(checkboxState)
                            .addComponent(checkboxCountry)
                            .addComponent(checkboxUniqueRegID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presentlbl)
                    .addComponent(lblPresent))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(absentlbl)
                            .addComponent(lblAbsent))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(checkboxContact)
                            .addGap(28, 28, 28)
                            .addComponent(checkboxAddress)
                            .addGap(30, 30, 30)
                            .addComponent(checkboxState)
                            .addGap(27, 27, 27)
                            .addComponent(checkboxCountry)
                            .addGap(29, 29, 29)
                            .addComponent(checkboxUniqueRegID)))
                    .addComponent(btnResetFilters, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void checkboxAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAddressActionPerformed

    private void btnResetFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFiltersActionPerformed
        txtSearch.setText("");
        fromDate.setDate(null);
        toDate.setDate(null);
        checkboxContact.setSelected(false);
        checkboxAddress.setSelected(false);
        checkboxState.setSelected(false);
        checkboxCountry.setSelected(false);
        checkboxUniqueRegID.setSelected(false);

        loadDataInTable();

    }//GEN-LAST:event_btnResetFiltersActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadDataInTable();
    }//GEN-LAST:event_formComponentShown

    private void checkboxContactItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxContactItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_checkboxContactItemStateChanged

    private void checkboxAddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxAddressItemStateChanged
        loadDataInTable();
    }//GEN-LAST:event_checkboxAddressItemStateChanged

    private void checkboxStateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxStateItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkboxStateItemStateChanged

    private void checkboxCountryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxCountryItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkboxCountryItemStateChanged

    private void checkboxUniqueRegIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxUniqueRegIDItemStateChanged
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_checkboxUniqueRegIDItemStateChanged

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        loadDataInTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAttendence().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel absentlbl;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnResetFilters;
    private javax.swing.JCheckBox checkboxAddress;
    private javax.swing.JCheckBox checkboxContact;
    private javax.swing.JCheckBox checkboxCountry;
    private javax.swing.JCheckBox checkboxState;
    private javax.swing.JCheckBox checkboxUniqueRegID;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAbsent;
    private javax.swing.JLabel lblPresent;
    private javax.swing.JLabel presentlbl;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables

    private void loadDataInTable() {

        List<String> columns = new ArrayList<>(Arrays.asList(
                "ID", "Name", "Gender", "Email", "Date", "CheckIn", "CheckOut", "WorkDuration"
        ));

        String searchText = txtSearch.getText();

        // ---------- FROM DATE ----------
        Date fromDateFromCal = fromDate.getDate();
        LocalDate fromLocalDate = null;

        if (fromDateFromCal != null) {
            fromLocalDate = fromDateFromCal
                    .toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
        }

        // ---------- TO DATE ----------
        Date toDateFromCal = toDate.getDate();
        LocalDate toLocalDate = null;

        if (toDateFromCal != null) {
            toLocalDate = toDateFromCal
                    .toInstant()
                    .atZone(ZoneId.systemDefault())
                    .toLocalDate();
        }

        Long daysBetween = null;
        if (fromLocalDate != null && toLocalDate != null) {
            daysBetween = countWeekdays(fromLocalDate, toLocalDate);
        }

        Boolean contactIncluded = checkboxContact.isSelected();
        Boolean addressIncluded = checkboxAddress.isSelected();
        Boolean stateIncluded = checkboxState.isSelected();
        Boolean countryIncluded = checkboxCountry.isSelected();
        Boolean uniqueRegIdIncluded = checkboxUniqueRegID.isSelected();
        String sqlQuery = "SELECT ud.id, ud.name, ud.gender, ud.email, "
                + "ua.date AS date, ua.checkin, ua.checkout, ua.workduration ";

        if (contactIncluded) {
            columns.add("Contact");
            sqlQuery += " , ud.contact";

        }

        if (addressIncluded) {
            columns.add("Address");
            sqlQuery += " , ud.address";
        }

        if (stateIncluded) {
            columns.add("State");
            sqlQuery += " , ud.state";
        }

        if (countryIncluded) {
            columns.add("Country");
            sqlQuery += " , ud.country";
        }

        if (uniqueRegIdIncluded) {
            columns.add("Unique Reg Id");
            sqlQuery += " , ud.uniqueregid";
        }

      sqlQuery += " FROM userdetails AS ud "
        + " INNER JOIN userattendence AS ua ON ud.id = ua.userid "
        + " WHERE 1=1 ";

        if (searchText != null && !searchText.trim().isEmpty()) {
             sqlQuery += " AND (ud.name LIKE '%" + searchText + "%' "
            + "OR ud.email LIKE '%" + searchText + "%') ";

            if (fromLocalDate != null && toLocalDate != null) {
                sqlQuery += " AND DATE(ua.date) BETWEEN '" + fromLocalDate + "' AND '" + toLocalDate + "'";

            }
        } else {
            if (fromLocalDate != null && toLocalDate != null) {
                sqlQuery += " AND DATE(ua.date) BETWEEN '" + fromLocalDate + "' AND '" + toLocalDate + "' ";
            } else if (fromLocalDate != null) {
                sqlQuery += " AND DATE(ua.date) >= '" + fromLocalDate + "' ";
            } else if (toLocalDate != null) {
                sqlQuery += " AND DATE(ua.date) <= '" + toLocalDate + "' ";
            }

        }

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns.toArray());
        userTable.setModel(model);
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sqlQuery);
            Long presentCount = 0l;
            Long absentCount = 0l;
            Set<String> emailList = new HashSet<>();
            while (rs.next()) {
                List<Object> row = new ArrayList<>();
                row.add(rs.getString("id"));
                row.add(rs.getString("name"));
                row.add(rs.getString("gender"));
                row.add(rs.getString("email"));
                emailList.add(rs.getString("email"));
                row.add(rs.getString("date"));
                row.add(rs.getString("checkin"));
                row.add(rs.getString("checkout"));
                row.add(rs.getString("workduration"));

                if (contactIncluded) {
                    row.add(rs.getString("contact"));
                }
                if (addressIncluded) {
                    row.add(rs.getString("address"));
                }

                if (stateIncluded) {
                    row.add(rs.getString("state"));
                }
                if (countryIncluded) {
                    row.add(rs.getString("country"));
                }
                if (uniqueRegIdIncluded) {
                    row.add(rs.getString("uniqueregid"));
                }

                if (rs.getString("checkout") == null) {
                    absentCount++;
                } else {
                    presentCount++;
                }

                model.addRow(row.toArray());
            }

            if (emailList.size() == 1) {
                lblPresent.setVisible(true);
                lblAbsent.setVisible(true);
                presentlbl.setVisible(true);
                absentlbl.setVisible(true);
                lblPresent.setText(presentCount.toString());
                if (daysBetween != null && daysBetween > 0) {
                    absentCount = daysBetween - presentCount;
                }
                lblAbsent.setText(absentCount.toString());

            } else {
                lblPresent.setVisible(false);
                lblAbsent.setVisible(false);
                presentlbl.setVisible(false);
                absentlbl.setVisible(false);
            }

        } catch (Exception ex) {
            ex.printStackTrace();   
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    private long countWeekdays(LocalDate start, LocalDate end) {
        long count = 0;
        LocalDate date = start;
        while (!date.isAfter(end)) { // while date <= end
            DayOfWeek day = date.getDayOfWeek();
            if (day != DayOfWeek.SATURDAY && day != DayOfWeek.SUNDAY) {
                count++;
            }
            date = date.plusDays(1);
        }
        return count;
    }

}
